services:
  - type: web
    name: vgmf-portal
    env: docker
    plan: standard
    region: singapore
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: SHIPROCKET_EMAIL
        sync: false
      - key: SHIPROCKET_PASSWORD
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /
